exp_name: t5_anonLLM
device: cuda:0
random_seed: 42

data:
  AmazonDataset:
    dataset_name: toys
    add_prefix_items_users: true
    items_start_from_1001: true

model:
  T5Rec:
    name_or_path: "google/flan-t5-small"
  n_epochs: 10
  train_batch_size: 32
  train_tasks:
    - SequentialSideInfoTask

eval:
  eval_batch_size: 16
  eval_tasks:
    SequentialSideInfoTask:
      - hit@10
      - hit@5
      - ndcg@10
      - ndcg@5
